### ISSUE TITLE
Invalid Unicode escape sequence

### ISSUE THREAD

**Issue by bennycode** [andersekdahl/karma-common-js#7]
When running your example (on Windows 10 Home), I am getting this error: `Uncaught SyntaxError: Invalid Unicode escape sequence`. The error occurs on this line: `var user = require('./user');` in `user-test.js`.

**Comment by pbartoszek** [comment]
I am also having exactly the same error. The pull request #6 fixes that. But then mocking doesn't work giving an error

`
     Error: Failed to resolve "./user"
            at require (node_modules/karma-common-js/start-client.js:69:13)
            at Context.<anonymous> (src/user-test.js:13:16)
`
